const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const {spawn}=require('node:child_process');const fs=require('node:fs');const path=require('node:path');const net=require('node:net');const crypto=require('node:crypto');const assert=require('node:assert/strict');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function freePort(){return new Promise(resolve=>{const s=net.createServer();s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>resolve(p));});});}
(async()=>{const root=path.resolve(__dirname,'..'),web=await freePort(),vpn=await freePort(),base='http://127.0.0.1:'+web;const output=path.join(root,'artifacts','browser',Date.now().toString());fs.mkdirSync(output,{recursive:true});const secret=()=>crypto.randomBytes(32).toString('base64');const adminPassword=secret();
const child=spawn('dotnet',[path.join(root,'src/ControlPlane/bin/Release/net10.0/EdgeVpn.ControlPlane.dll')],{cwd:path.join(root,'src/ControlPlane'),windowsHide:true,env:{...process.env,ASPNETCORE_ENVIRONMENT:'Development',Mail__PickupDirectory:path.join(output,'mail'),ASPNETCORE_URLS:base,PublicUrl:base,DataDirectory:path.join(output,'data'),AdminKey:secret(),PunchNodeKey:secret(),RelayNodeKey:secret(),Coordinator__FirstPort:String(vpn),Coordinator__Capacity:'2',Coordinator__Hosts__0:'127.0.0.1',BootstrapAdmin__Email:'admin@example.com',BootstrapAdmin__Password:adminPassword,Logging__LogLevel__Default:'Warning'}});child.stdout.pipe(fs.createWriteStream(path.join(output,'server.log')));child.stderr.pipe(fs.createWriteStream(path.join(output,'server-error.log')));let browser;
try{for(let i=0;i<100;i++){try{if((await fetch(base+'/health')).ok)break;}catch{}await delay(100);}
assert.equal((await fetch(base+'/console',{redirect:'manual'})).status,302);assert.equal((await fetch(base+'/Pages/console.html')).status,404);
browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_PATH||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});const page=await context.newPage(),errors=[];page.on('pageerror',err=>errors.push(err.message));
await page.goto(base);await page.screenshot({path:path.join(output,'home-desktop.png'),fullPage:true});assert.match(await page.title(),/P2P/);await page.goto(base+'/register');await page.screenshot({path:path.join(output,'register.png'),fullPage:true});
await page.locator('[name=email]').fill('browser@example.com');await page.locator('[name=password]').fill('Browser-password-2026');await page.locator('[name=confirmPassword]').fill('Browser-password-2026');await page.locator('#send-code').click();await page.waitForFunction(()=>document.getElementById('code-note').textContent.includes('已发送'));const mail=fs.readdirSync(path.join(output,'mail')).map(f=>JSON.parse(fs.readFileSync(path.join(output,'mail',f),'utf8'))).find(m=>m.To==='browser@example.com');await page.locator('[name=verificationCode]').fill(mail.Body.match(/\b[0-9]{6}\b/)[0]);await page.locator('#auth-submit').click();await page.locator('#recovery-dialog').waitFor({state:'visible'});const recovery=await page.locator('#recovery-value').inputValue();assert.ok(recovery.length>30);await page.locator('#continue-account').click();await page.waitForURL('**/console#setup');await page.locator('#setup-network').waitFor();
assert.equal((await context.cookies()).find(c=>c.name==='edge_session').httpOnly,true);assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);
const me=await (await context.request.get(base+'/api/me')).json();const headers={'X-CSRF-Token':me.csrfToken};assert.equal((await context.request.post(base+'/api/networks',{data:{name:'blocked'}})).status(),403);assert.equal((await context.request.post(base+'/api/networks',{headers:{...headers,Origin:'https://untrusted.example'},data:{name:'blocked'}})).status(),403);assert.equal((await context.request.get(base+'/admin/accounts')).status(),401);
await page.locator('#setup-network [name=name]').fill('我的工作室');await page.locator('#setup-network summary').click();await page.locator('#setup-network [name=subnet]').fill('172.22.42.0/24');await page.locator('#setup-network button[type=submit]').click();await page.waitForURL(/#setup\//);await page.locator('#setup-device').waitFor();const networkId=page.url().split('/').pop();await page.goto(base+'/console#networks/'+networkId);
await page.locator('[data-action=tab][data-id=groups]').click();await page.locator('[data-action=new-group]').click();await page.locator('#action-dialog [name=name]').fill('研发设备');await page.locator('#modal-submit').click();await page.locator('.group-card h3').filter({hasText:'研发设备'}).waitFor();
await page.locator('[data-action=tab][data-id=keys]').click();await page.locator('[data-action=new-key]').click();await page.locator('#action-dialog summary').click();await page.locator('#action-dialog [name=name]').fill('测试邀请');await page.locator('#action-dialog [name=groupId]').selectOption({label:'研发设备'});await page.locator('#modal-submit').click();await page.locator('#join-close').waitFor();const key=await page.locator('#action-dialog textarea').inputValue();await page.locator('#join-close').click();
await page.goto(base+'/console#join');await page.locator('#join-form [name=name]').fill('工作电脑');await page.locator('#join-form [name=key]').fill(key);await page.locator('#join-form button').click();await page.locator('#secret-close').waitFor();const profile=JSON.parse(await page.locator('#action-dialog textarea').inputValue());assert.equal(profile.relayUrls.length,0);assert.equal(profile.controlUrl,base);assert.equal(profile.subnet,'172.22.42.0/24');await page.locator('#secret-close').click();
await page.goto(base+'/console#networks/'+networkId);await page.locator('[data-action=tab][data-id=devices]').click();await page.getByText('工作电脑',{exact:true}).waitFor();await page.screenshot({path:path.join(output,'devices-desktop.png'),fullPage:true});
await page.goto(base+'/console#overview');await page.locator('h1').filter({hasText:'连接你的世界'}).waitFor();await page.screenshot({path:path.join(output,'console-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(output,'console-mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.goto(base);await page.screenshot({path:path.join(output,'home-mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.goto(base+'/downloads');await page.locator('.download-card').first().waitFor();const catalog=await (await context.request.get(base+'/api/downloads')).json();assert.ok(catalog.length>=5);for(const item of catalog){const r=await context.request.get(base+item.url,{headers:{Range:'bytes=0-3'}});assert.equal(r.status(),206);assert.equal((await r.body()).toString('hex'),'504b0304');}
assert.equal((await context.request.get(base+'/downloads/not-allowed.zip')).status(),404);
const installerPath=path.join(output,'install.ps1');fs.writeFileSync(installerPath,await(await context.request.get(base+'/install.ps1')).body());
await new Promise((resolve,reject)=>{const installer=spawn('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-File',installerPath,'-DownloadOnly','-Destination',path.join(output,'installer')],{windowsHide:true});let log='';installer.stdout.on('data',d=>log+=d);installer.stderr.on('data',d=>log+=d);installer.on('exit',code=>code===0?resolve():reject(Error('Installer download check failed: '+log)));});
assert.ok(fs.existsSync(path.join(output,'installer/client/P2PVpnClient.exe')));

const admin=await browser.newContext();let r=await admin.request.post(base+'/api/login',{headers:{'X-Session-Mode':'cookie'},data:{email:'admin@example.com',password:adminPassword}});assert.equal(r.status(),200);const adminAuth=await r.json(),ah={'X-CSRF-Token':adminAuth.csrfToken};
const adminPage=await admin.newPage();await adminPage.goto(base+'/ops#nodes');await adminPage.getByText('还没有注册独立节点',{exact:true}).waitFor();await adminPage.screenshot({path:path.join(output,'ops-nodes.png'),fullPage:true});
await adminPage.goto(base+'/ops#mail');await adminPage.locator('#mail-form').waitFor();await adminPage.screenshot({path:path.join(output,'ops-mail.png'),fullPage:true});
let mailResponse=await admin.request.put(base+'/admin/mail',{headers:ah,data:{enabled:true,host:'smtp.example.com',port:465,security:'ssl',username:'sender@example.com',password:'test-authorized-smtp-secret',fromEmail:'sender@example.com',fromName:'P2P VPN',notificationEmail:'notice@example.com',notifyRegistrations:true,notifyMembershipChanges:true}});assert.equal(mailResponse.status(),200);assert.ok(!(await mailResponse.text()).includes('test-authorized-smtp-secret'));assert.ok(!fs.readFileSync(path.join(output,'data/state.json'),'utf8').includes('test-authorized-smtp-secret'));
assert.equal((await admin.request.post(base+'/admin/mail/test',{headers:ah,data:{email:'notice@example.com'}})).status(),200);
await adminPage.goto(base+'/ops#devices');await adminPage.locator('h1').filter({hasText:'全平台设备'}).waitFor();await adminPage.screenshot({path:path.join(output,'ops-devices.png'),fullPage:true});
const detail=await(await admin.request.get(base+'/admin/accounts/'+me.id)).json();assert.equal(detail.account.emailVerifiedAt!==null,true);assert.equal(detail.devices.length,1);assert.equal(detail.networks[0].subnet,'172.22.42.0/24');
assert.equal((await context.request.post(base+'/api/networks',{headers,data:{name:'overlap',subnet:'172.22.42.0/25'}})).status(),409);assert.equal((await context.request.post(base+'/api/networks',{headers,data:{name:'bad',subnet:'8.8.8.0/24'}})).status(),400);assert.equal((await context.request.put(base+'/api/networks/'+networkId+'/subnet',{headers,data:{name:'existing',subnet:'10.90.0.0/24'}})).status(),409);
for(const installer of ['/install.cmd','/install.ps1','/install.sh']){const script=await context.request.get(base+installer);assert.equal(script.status(),200);assert.ok(!(await script.text()).includes(key));}
r=await admin.request.post(base+'/admin/nodes',{headers:ah,data:{name:'Backup test',role:'punch',endpoint:'127.0.0.2'}});assert.equal(r.status(),200);const node=await r.json(),nh={'X-Node-Key':node.nodeKey};assert.equal((await context.request.get(base+'/internal/punch/snapshot',{headers:nh})).status(),200);assert.equal((await context.request.post(base+'/internal/relay/inspect',{headers:{...nh,...headers},data:{token:profile.deviceToken}})).status(),401);
assert.equal((await admin.request.post(base+'/internal/node/heartbeat',{headers:{...nh,...ah},data:{nodeId:node.id,role:'punch',version:'0.3.0',deviceIds:[profile.deviceId,'fake-device-id']}})).status(),204);
r=await context.request.get(base+'/api/device/profile',{headers:{Authorization:'Bearer '+profile.deviceToken}});assert.equal(r.status(),200);assert.ok((await r.json()).coordinatorServers.some(s=>s.startsWith('127.0.0.2:')));
const nodeDevices=await(await admin.request.get(base+'/admin/devices')).json();assert.ok(nodeDevices.find(x=>x.id===profile.deviceId).online);await admin.request.delete(base+'/admin/nodes/'+node.id,{headers:ah});assert.ok(!(await(await admin.request.get(base+'/admin/devices')).json()).find(x=>x.id===profile.deviceId).online);assert.equal((await context.request.get(base+'/internal/punch/snapshot',{headers:nh})).status(),401);
r=await context.request.post(base+'/api/networks/'+networkId+'/devices/'+profile.deviceId+'/configuration',{headers});assert.equal(r.status(),200);const replacement=await r.json();assert.notEqual(replacement.deviceToken,profile.deviceToken);assert.equal((await context.request.get(base+'/api/device/profile',{headers:{Authorization:'Bearer '+profile.deviceToken}})).status(),401);
const second=await browser.newContext();r=await second.request.post(base+'/api/login',{headers:{'X-Session-Mode':'cookie'},data:{email:'browser@example.com',password:'Browser-password-2026'}});assert.equal(r.status(),200);await context.request.delete(base+'/api/security/sessions',{headers});assert.equal((await second.request.get(base+'/api/me')).status(),401);
r=await context.request.post(base+'/api/security/recovery-key',{headers,data:{currentPassword:'Browser-password-2026',newPassword:''}});assert.equal(r.status(),200);const updatedRecovery=(await r.json()).recoveryCode;assert.notEqual(updatedRecovery,recovery);
r=await second.request.post(base+'/api/auth/recover',{data:{email:'browser@example.com',recoveryCode:recovery,newPassword:'Recovered-password-2026'}});assert.equal(r.status(),401);
r=await second.request.post(base+'/api/auth/recover',{data:{email:'browser@example.com',recoveryCode:updatedRecovery,newPassword:'Recovered-password-2026'}});assert.equal(r.status(),200);assert.equal((await context.request.get(base+'/api/me')).status(),401);
r=await second.request.post(base+'/api/login',{headers:{'X-Session-Mode':'cookie'},data:{email:'browser@example.com',password:'Recovered-password-2026'}});assert.equal(r.status(),200);const lastAuth=await r.json();r=await second.request.post(base+'/api/security/password',{headers:{'X-CSRF-Token':lastAuth.csrfToken},data:{currentPassword:'Recovered-password-2026',newPassword:'Updated-password-2026'}});assert.equal(r.status(),204);assert.equal((await second.request.get(base+'/api/me')).status(),401);
await adminPage.goto(base+'/ops#accounts/'+me.id);await adminPage.locator('h1').filter({hasText:'browser@example.com'}).waitFor();await adminPage.screenshot({path:path.join(output,'ops-user-detail.png'),fullPage:true});await adminPage.setViewportSize({width:390,height:844});await adminPage.goto(base+'/ops#mail');await adminPage.locator('#mail-form').waitFor();assert.equal(await adminPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await adminPage.screenshot({path:path.join(output,'ops-mail-mobile.png'),fullPage:true});assert.deepEqual(errors,[]);console.log('PASS: public pages, registration, authenticated UI, networks/groups/keys/enrollment, mobile layout, real downloads, cookie/CSRF/origin/tenant/admin guards, node heartbeat and role/revocation, device credential rotation, sessions, recovery and password revocation.');console.log('Screenshots: '+output);
}finally{if(browser)await browser.close();child.kill();}
})().catch(err=>{console.error(err);process.exitCode=1;});
