const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const {spawn}=require('node:child_process'),fs=require('node:fs'),path=require('node:path'),net=require('node:net'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function port(){return new Promise(r=>{let s=net.createServer();s.listen(0,'127.0.0.1',()=>{let p=s.address().port;s.close(()=>r(p));});});}
async function run(command,args){return new Promise((resolve,reject)=>{let log='';const p=spawn(command,args,{windowsHide:true});p.stdout.on('data',d=>log+=d);p.stderr.on('data',d=>log+=d);p.on('exit',c=>c===0?resolve(log):reject(Error(command+' failed: '+log)));});}
(async()=>{const root=path.resolve(__dirname,'..'),base='http://127.0.0.1:'+await port(),output=path.join(root,'artifacts','setup-check',Date.now().toString());fs.mkdirSync(output,{recursive:true});const secret=()=>crypto.randomBytes(32).toString('base64url'),password=secret(),adminKey=secret();
const server=spawn('dotnet',[path.join(root,'src/ControlPlane/bin/Release/net10.0/EdgeVpn.ControlPlane.dll')],{cwd:path.join(root,'src/ControlPlane'),windowsHide:true,env:{...process.env,ASPNETCORE_ENVIRONMENT:'Development',ASPNETCORE_URLS:base,PublicUrl:base,DataDirectory:path.join(output,'data'),AdminKey:adminKey,PunchNodeKey:secret(),RelayNodeKey:secret(),Coordinator__FirstPort:String(await port()),Coordinator__Capacity:'4',BootstrapAdmin__Email:'setup@example.com',BootstrapAdmin__Password:password,Logging__LogLevel__Default:'Warning'}});server.stdout.pipe(fs.createWriteStream(path.join(output,'server.log')));server.stderr.pipe(fs.createWriteStream(path.join(output,'error.log')));let browser;
try{for(let i=0;i<100;i++){try{if((await fetch(base+'/health')).ok)break;}catch{}await delay(100);}
 browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];page.on('pageerror',err=>errors.push(err.message));
 let response=await context.request.post(base+'/api/login',{headers:{'X-Session-Mode':'cookie'},data:{email:'setup@example.com',password}});assert.equal(response.status(),200);const session=await response.json(),headers={'X-CSRF-Token':session.csrfToken};
 await page.goto(base+'/console');await page.waitForURL('**/console#setup');await page.locator('#setup-network').waitFor();await page.screenshot({path:path.join(output,'01-network.png'),fullPage:true});
 await page.locator('#setup-network [name=name]').fill('我的远程工作室');await page.locator('#setup-network button[type=submit]').click();await page.locator('#setup-device').waitFor();const id=page.url().split('/').pop();await page.screenshot({path:path.join(output,'02-device.png'),fullPage:true});
 await page.locator('#setup-device [name=name]').fill('办公电脑');const created=page.waitForResponse(r=>r.url().endsWith('/installations')&&r.request().method()==='POST');await page.locator('#setup-device button[type=submit]').click();const install=await(await created).json();await page.locator('#setup-command').waitFor();const command=await page.locator('#setup-command').inputValue();assert.equal(command,install.command);assert.match(command,/-Ticket '[A-Za-z0-9_-]{43}'/);assert.ok(!command.includes('/api/enroll'));const ticket=command.match(/-Ticket '([^']+)'/)[1];const endpoint=base+'/api/networks/'+id+'/installations/'+install.id;
 await page.screenshot({path:path.join(output,'03-command.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(output,'03-command-mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 const networks=await(await context.request.get(base+'/api/networks')).json(),network=networks.find(n=>n.id===id);assert.equal(network.devices.length,0);assert.ok(!JSON.stringify(network).includes(ticket));assert.ok(!fs.readFileSync(path.join(output,'data/state.json'),'utf8').includes(ticket));assert.equal((await(await context.request.get(endpoint)).json()).status,'pending');assert.equal((await fetch(endpoint)).status,401);
 const publicScript=await(await fetch(base+'/install.ps1')).text();assert.ok(!publicScript.includes(ticket));assert.ok(!publicScript.includes('__INSTALL_TICKET__'));assert.equal((await(await context.request.get(endpoint)).json()).status,'pending');
 // Run the actual generated PowerShell script through package download, hash verification,
 // credential redemption and real client configuration check; deliberately skip OS service install.
 const script=path.join(output,'personal.ps1'),stage=path.join(output,'configure');fs.writeFileSync(script,'\ufeff'+install.script);await run('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-File',script,'-ConfigureOnly','-Destination',stage]);const profile=JSON.parse(fs.readFileSync(path.join(stage,'client/client.json'),'utf8'));assert.equal(profile.controlUrl,base);assert.equal(profile.subnet,network.subnet);assert.ok(profile.deviceToken);
 let status=await(await context.request.get(endpoint)).json();assert.equal(status.status,'enrolled');assert.equal(status.deviceId,profile.deviceId);await page.locator('#setup-status b').filter({hasText:'已自动加入网络'}).waitFor();
 let authIndex=0;const redeem=(token,claim,platform='win-x64')=>fetch(base+'/api/install/redeem',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json','X-Forwarded-For':'198.51.100.'+(++authIndex)},body:JSON.stringify({claim,platform})});
 const claim=fs.readFileSync(path.join(stage,'claim.txt'),'utf8');let r=await redeem(ticket,claim);assert.equal(r.status,200);assert.equal((await r.json()).deviceToken,profile.deviceToken);assert.equal((await redeem(ticket,secret())).status,401);assert.equal((await redeem(ticket,claim,'linux-x64')).status,400);
 assert.equal((await context.request.post(base+'/api/networks/'+id+'/installations',{data:{name:'blocked',platform:'win-x64',groupId:network.groups[0].id}})).status(),403);
 const foreign=await context.request.post(base+'/api/networks/not-owned/installations',{headers,data:{name:'blocked',platform:'win-x64',groupId:network.groups[0].id}});assert.equal(foreign.status(),404);
 // Linux API contract; the actual POSIX shell installer is exercised separately on Linux.
 r=await context.request.post(base+'/api/networks/'+id+'/installations',{headers,data:{name:'Linux "quoted" $(no-shell-execution)',platform:'linux-x64',groupId:network.groups[0].id}});assert.equal(r.status(),200);const linux=await r.json();assert.ok(!linux.script.includes('$(no-shell-execution)'));assert.ok(!linux.script.includes('python'));assert.ok(!linux.script.includes('__LINUX_'));const linuxToken=linux.command.match(/--ticket '([^']+)'/)[1];const linuxClaim=secret();r=await redeem(linuxToken,linuxClaim,'linux-x64');assert.equal(r.status,200);const lp=await r.json();assert.notEqual(lp.deviceId,profile.deviceId);assert.equal(lp.subnet,profile.subnet);
 // Heartbeat proves UI success depends on an actual active node connection report.
 r=await context.request.post(base+'/admin/nodes',{headers,data:{name:'Setup verification',role:'punch',endpoint:'127.0.0.2'}});const node=await r.json();await context.request.post(base+'/internal/node/heartbeat',{headers:{...headers,'X-Node-Key':node.nodeKey},data:{nodeId:node.id,role:'punch',version:'test',deviceIds:[profile.deviceId]}});await page.locator('#setup-status b').filter({hasText:'设备已上线'}).waitFor();await page.screenshot({path:path.join(output,'04-online-mobile.png'),fullPage:true});
 await context.request.delete(endpoint,{headers});assert.equal((await redeem(ticket,claim)).status,401);
 // Rotation and revocation cannot be undone by retrying an install ticket.
 await context.request.post(base+'/api/networks/'+id+'/devices/'+lp.deviceId+'/configuration',{headers});assert.equal((await redeem(linuxToken,linuxClaim,'linux-x64')).status,401);
 await page.goto(base+'/console#networks/'+id);await page.locator('[data-action=add-device]').click();await page.locator('#setup-device').waitFor();assert.equal(await page.locator('#setup-device [name=name]').inputValue(),'新设备');// A generic Linux ticket accepts one supported architecture, then binds to it.
 for(const rid of ['linux-arm','linux-arm64','linux-x64']){
  const result=await context.request.post(base+'/api/networks/'+id+'/installations',{headers,data:{name:'Architecture '+rid,platform:'linux',groupId:network.groups[0].id}});assert.equal(result.status(),200);const t=await result.json(),token=t.command.match(/--ticket '([^']+)'/)[1],claim=secret();
  assert.equal((await redeem(token,claim,'linux-x86')).status,400);assert.equal((await redeem(token,claim,rid)).status,200);assert.equal((await redeem(token,claim,rid)).status,200);assert.equal((await redeem(token,claim,rid==='linux-arm'?'linux-arm64':'linux-arm')).status,400);
 }
 assert.equal((await context.request.post(base+'/api/networks/'+id+'/installations',{headers,data:{name:'Unsupported',platform:'linux-x86',groupId:network.groups[0].id}})).status(),400);
 const catalog=await(await context.request.get(base+'/api/downloads')).json();for(const rid of ['linux-arm','linux-arm64','linux-x64'])assert.ok(catalog.some(x=>x.kind==='client'&&x.platform===rid));
 // Expiry is enforced at redemption, not just displayed in the UI.
 const expiry=await(await context.request.post(base+'/api/networks/'+id+'/installations',{headers,data:{name:'expire-test',platform:'win-x64',groupId:network.groups[0].id}})).json();const expiredToken=expiry.command.match(/-Ticket '([^']+)'/)[1];const stateFile=path.join(output,'data/state.json'),state=JSON.parse(fs.readFileSync(stateFile,'utf8'));state.InstallTickets.find(t=>t.Id===expiry.id).ExpiresAt='2020-01-01T00:00:00+00:00';fs.writeFileSync(stateFile+'.test',JSON.stringify(state));fs.renameSync(stateFile+'.test',stateFile);assert.equal((await redeem(expiredToken,secret())).status,401);assert.equal((await(await context.request.get(base+'/api/networks/'+id+'/installations/'+expiry.id)).json()).status,'expired');
 assert.deepEqual(errors,[]);
 console.log('PASS: guided onboarding, generated Windows installer with real download/hash/configuration check, Linux automatic enrollment code, no preview consumption, hashed tickets, same-machine retry, replay/CSRF/tenant guards, revocation, rotation, live online feedback and mobile layout.');console.log('Screenshots: '+output);
}finally{if(browser)await browser.close();server.kill();}
})().catch(e=>{console.error(e);process.exitCode=1;});
